
#ifndef __PAM_EVENT_H__
#define __PAM_EVENT_H__

#include "osi_api.h"

#define EV_PAM_GNSS_BASE (0)
#define EV_PAM_GNSS_END_ (6050)

typedef enum
{
    PAM_APP_MN_GPS_DOWNLOAD_REQ, //= EV_PAM_GNSS_BASE,
    PAM_APP_MN_GPS_INIT_REQ,
    PAM_APP_MN_GPS_START_REQ,
    PAM_APP_MN_GPS_STOP_REQ,
    PAM_APP_MN_GPS_RESET_REQ,
    PAM_APP_MN_GPS_READ_STATUS_REQ,
    PAM_APP_MN_GPS_READ_INFO_REQ,
    PAM_APP_MN_GPS_OUTPUT_REQ,
    PAM_APP_MN_GPS_POWEROFF_REQ,
    PAM_APP_MN_GPS_PDP_INFO_REQ,
    PAM_APP_MN_GPS_REPORT_REQ,
    PAM_APP_MN_GPS_ASSERT_REQ,
    PAM_APP_MN_GPS_SET_GNSS_MODE_REQ,
    PAM_APP_MN_GPS_DEL_AID_DATA_REQ,
    PAM_MN_GPS_DOWNLOAD_REQ, //--------->14
    PAM_MN_GPS_INIT_REQ,     //15
    PAM_MN_GPS_START_REQ,    //16
    PAM_MN_GPS_STOP_REQ,
    PAM_MN_GPS_RESET_REQ,
    PAM_MN_GPS_READ_STATUS_REQ,
    PAM_MN_GPS_READ_INFO_REQ, //-------->20
    PAM_MN_GPS_OUTPUT_REQ,
    PAM_MN_GPS_POWEROFF_REQ,
    PAM_MN_GPS_PDP_INFO_REQ,
    PAM_MN_GPS_REPORT_REQ,
    PAM_MN_GPS_ASSERT_REQ,
    PAM_MN_GPS_DOWNLOAD_CNF, //------->26
    PAM_MN_GPS_INIT_CNF,
    PAM_MN_GPS_START_CNF,
    PAM_MN_GPS_STOP_CNF,
    PAM_MN_GPS_RESET_CNF,
    PAM_MN_GPS_READ_STATUS_CNF,
    PAM_MN_GPS_READ_INFO_CNF, //-------->32
    PAM_MN_GPS_OUTPUT_CNF,
    PAM_MN_GPS_OUTPUT_INFO_IND,
    PAM_MN_GPS_POWEROFF_CNF,
    PAM_MN_GPS_ERR_IND,
    PAM_MN_GPS_FIX_IND, //---->37
    PAM_MN_GPS_REPORT_CNF,
    PAM_MN_GPS_LOCATION_INFO_IND,
    PAM_MN_GPS_SATELLITE_INFO_IND,
    PAM_MN_GPS_SET_GNSS_MODE_REQ, //----->41
    PAM_MN_GPS_SET_GNSS_MODE_CNF,
    PAM_MSENSOR_GPS_SMD_INT,
    PAM_MN_GPS_DATA_SOCKET_IND,
    PAM_LIBGPS_WATCHDOG_REQ,
    PAM_MN_GPS_DEL_AID_DATA_REQ,
    PAM_MN_GPS_DEL_AID_DATA_CNF,
    PAM_MN_GPS_STARTMODE_AGNSS_IND, //----->48
    PAM_MN_GPS_PDP_INFO_CNF,
    PAM_MN_GPS_RUN_REQ,
    PAM_MN_GPS_RUN_CNF, //--->51
    PAM_MN_GPS_SLEEP_IND,
    PAM_MN_GPS_END_SIGNAL

} PAM_GNSS_EVENT_ID;

static const osiValueStrMap_t gPamEventNames[] = {
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_DOWNLOAD_CNF)}, // 10
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_INIT_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_START_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_STOP_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_RESET_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_READ_STATUS_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_READ_INFO_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_OUTPUT_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_OUTPUT_INFO_IND)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_POWEROFF_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_ERR_IND)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_FIX_IND)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_REPORT_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_LOCATION_INFO_IND)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_SATELLITE_INFO_IND)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_SET_GNSS_MODE_REQ)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_SET_GNSS_MODE_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MSENSOR_GPS_SMD_INT)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_DATA_SOCKET_IND)},
    {OSI_VSMAP_CONST_DECL(PAM_LIBGPS_WATCHDOG_REQ)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_DEL_AID_DATA_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_STARTMODE_AGNSS_IND)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_SLEEP_IND)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_PDP_INFO_CNF)},
    {OSI_VSMAP_CONST_DECL(PAM_MN_GPS_RUN_CNF)},
};

#endif
