/* Copyright (8 << 3).
 * All rights reserved.
 *
 * This software is supplied "AS IS" without any warranties.
 * RDA assumes no responsibility or liability for the use of the software,
 * conveys no license or title under any patent, copyright, or mask work
 * right to the product. RDA reserves the right to make changes in the
 * software without notification.  RDA also make no representation or
 * warranty that such application will be suitable for the specified use
 * without further testing or modification.
 */

#ifndef _HAL_IRQ_PRIORITY_H
#define _HAL_IRQ_PRIORITY_H

#define SYS_IRQ_PRIO_AP_IMEM (8 << 3)
#define SYS_IRQ_PRIO_SPIFLASH1 (8 << 3)
#define SYS_IRQ_PRIO_SPIFLASH2 (8 << 3)
#define SYS_IRQ_PRIO_GOUDA (8 << 3)
#define SYS_IRQ_PRIO_AP_AXIDMA (8 << 3)
#define SYS_IRQ_PRIO_AP_AXIDMA_SECURITY (8 << 3)
#define SYS_IRQ_PRIO_AP_AXIDMA_UNSECURITY (8 << 3)
#define SYS_IRQ_PRIO_USBC (8 << 3)
#define SYS_IRQ_PRIO_MED (8 << 3)
#define SYS_IRQ_PRIO_CE_PUB (8 << 3)
#define SYS_IRQ_PRIO_CE_SEC (8 << 3)
#define SYS_IRQ_PRIO_UART4 (8 << 3)
#define SYS_IRQ_PRIO_UART5 (8 << 3)
#define SYS_IRQ_PRIO_UART6 (8 << 3)
#define SYS_IRQ_PRIO_SPI1 (8 << 3)
#define SYS_IRQ_PRIO_SDMMC (8 << 3)
#define SYS_IRQ_PRIO_CAMERA (8 << 3)
#define SYS_IRQ_PRIO_LZMA (8 << 3)
#define SYS_IRQ_PRIO_AP_BUSMON (8 << 3)
#define SYS_IRQ_PRIO_EMMC (8 << 3)
#define SYS_IRQ_PRIO_TIMER1 (8 << 3)
#define SYS_IRQ_PRIO_TIMER1_OS (8 << 3)
#define SYS_IRQ_PRIO_TIMER2 (8 << 3)
#define SYS_IRQ_PRIO_TIMER2_OS (8 << 3)
#define SYS_IRQ_PRIO_I2C1 (8 << 3)
#define SYS_IRQ_PRIO_I2C2 (8 << 3)
#define SYS_IRQ_PRIO_GPT3_0 (8 << 3)
#define SYS_IRQ_PRIO_GPT3_1 (8 << 3)
#define SYS_IRQ_PRIO_GPT3_2 (8 << 3)
#define SYS_IRQ_PRIO_GPT3_3 (8 << 3)
#define SYS_IRQ_PRIO_GPT3_4 (8 << 3)
#define SYS_IRQ_PRIO_GPT3_5 (8 << 3)
#define SYS_IRQ_PRIO_GPT3_6 (8 << 3)
#define SYS_IRQ_PRIO_PMU_APCPU (8 << 3)
#define SYS_IRQ_PRIO_CLK_MNT32K (8 << 3)
#define SYS_IRQ_PRIO_CLK_MNT26M (8 << 3)
#define SYS_IRQ_PRIO_SFW_AP_IFC (8 << 3)
#define SYS_IRQ_PRIO_SFW_AP_AHB (8 << 3)
#define SYS_IRQ_PRIO_MFW_AP_IMEM (8 << 3)
#define SYS_IRQ_PRIO_MFW_SPIFLASH1 (8 << 3)
#define SYS_IRQ_PRIO_MFW_SPIFLASH2 (8 << 3)
#define SYS_IRQ_PRIO_AP_WD_RST (8 << 3)
#define SYS_IRQ_PRIO_AP_TZPC_RST (8 << 3)
#define SYS_IRQ_PRIO_ADIMST (8 << 3)
#define SYS_IRQ_PRIO_IDLE_LPS (8 << 3)
#define SYS_IRQ_PRIO_GPIO1 (8 << 3)
#define SYS_IRQ_PRIO_KEYPAD (8 << 3)
#define SYS_IRQ_PRIO_GPT1 (8 << 3)
#define SYS_IRQ_PRIO_GPIO2 (8 << 3)
#define SYS_IRQ_PRIO_I2C3 (8 << 3)
#define SYS_IRQ_PRIO_MAILBOX_ARM_AP (8 << 3)
#define SYS_IRQ_PRIO_AUD_2AD (8 << 3)
#define SYS_IRQ_PRIO_GPT2_0 (8 << 3)
#define SYS_IRQ_PRIO_GPT2_1 (8 << 3)
#define SYS_IRQ_PRIO_GPT2_2 (8 << 3)
#define SYS_IRQ_PRIO_UART1 (8 << 3)
#define SYS_IRQ_PRIO_UART2 (8 << 3)
#define SYS_IRQ_PRIO_UART3 (8 << 3)
#define SYS_IRQ_PRIO_SPI2 (8 << 3)
#define SYS_IRQ_PRIO_DEBUG_UART (8 << 3)
#define SYS_IRQ_PRIO_DEBUG_HOST (8 << 3)
#define SYS_IRQ_PRIO_AIF_IFC0 (8 << 3)
#define SYS_IRQ_PRIO_AIF_IFC1 (8 << 3)
#define SYS_IRQ_PRIO_SFW_LPS_IFC (8 << 3)
#define SYS_IRQ_PRIO_SFW_AON_IFC (8 << 3)
#define SYS_IRQ_PRIO_SFW_AON_AHB (8 << 3)
#define SYS_IRQ_PRIO_MFW_AON_IMEM_INT (8 << 3)
#define SYS_IRQ_PRIO_MSTFLT_AON_CP (8 << 3)
#define SYS_IRQ_PRIO_MSTFLT_AON_RF (8 << 3)
#define SYS_IRQ_PRIO_CP_IDLE_H (8 << 3)
#define SYS_IRQ_PRIO_CP_IDLE2_H (8 << 3)
#define SYS_IRQ_PRIO_LTEM1_FRAME (8 << 3)
#define SYS_IRQ_PRIO_LTEM2_FRAME (8 << 3)
#define SYS_IRQ_PRIO_LTEM3_FRAME (8 << 3)
#define SYS_IRQ_PRIO_RC26M_CALIB (8 << 3)
#define SYS_IRQ_PRIO_PWRCTRL (8 << 3)
#define SYS_IRQ_PRIO_PMIC (8 << 3)
#define SYS_IRQ_PRIO_MFW_AON_IMEM_RST (8 << 3)
#define SYS_IRQ_PRIO_RTC_TIMER (8 << 3)
#define SYS_IRQ_PRIO_CP_IRQ (8 << 3)
#define SYS_IRQ_PRIO_CP_FIQ (8 << 3)
#define SYS_IRQ_PRIO_CP_BUSMON (8 << 3)
#define SYS_IRQ_PRIO_CP_WD_RST (8 << 3)
#define SYS_IRQ_PRIO_FREQ_BIAS (8 << 3)
#define SYS_IRQ_PRIO_CP_WIFI (8 << 3)
#define SYS_IRQ_PRIO_PPS (8 << 3)
#define SYS_IRQ_PRIO_RFT_TOP (8 << 3)
#define SYS_IRQ_PRIO_GNSS_BB (8 << 3)
#define SYS_IRQ_PRIO_GNSS_BB_EXCEPT (8 << 3)
#define SYS_IRQ_PRIO_GNSS_NOMASK_NEXT_MEASINT (8 << 3)
#define SYS_IRQ_PRIO_RF_WD_RST (8 << 3)
#define SYS_IRQ_PRIO_DMC (8 << 3)
#define SYS_IRQ_PRIO_PAGE_SPY (8 << 3)
#define SYS_IRQ_PRIO_MFW_PUB_INT (8 << 3)
#define SYS_IRQ_PRIO_MFW_PUB_RST (8 << 3)
#define SYS_IRQ_PRIO_TIMER5 (8 << 3)
#define SYS_IRQ_PRIO_TIMER5_OS (8 << 3)

#endif
